In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [19]:
dataset = pd.read_csv('train.csv')
dataset.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [20]:
X_vals = dataset.iloc[:,1:].values
y_vals = dataset.iloc[:,0].values

In [21]:
X_vals = X_vals/255.0
y_vals = y_vals.astype(np.float64)
print(X_vals,X_vals.shape, X_vals.dtype)
print(y_vals, y_vals.shape, y_vals.dtype)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] (42000, 784) float64
[1. 0. 1. ... 7. 6. 9.] (42000,) float64


In [22]:
X_vals = np.concatenate((np.ones((X_vals.shape[0],1), dtype=float),X_vals), axis=1)

In [23]:
X_vals.shape

(42000, 785)

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X_vals, y_vals, test_size = 0.2, random_state=0)

In [26]:
X_train = X_train.T
X_test = X_test.T
print(X_train.shape)
print(X_test.shape)

(785, 33600)
(785, 8400)


In [28]:
y_train = y_train.reshape(1, X_train.shape[1])
y_test = y_test.reshape(1, X_test.shape[1])
print(y_train.shape)
print(y_test.shape)

(1, 33600)
(1, 8400)


In [ ]:
# one hot encoding the vector y
for i in range(y_train.shape[1]):
    temp = np.zeros((10), dtype=np.float64)
    if y_train[i]

##### PREPROCESSING IS DONE(THOUGH IT WAS NONE :') ), READY FOR MODEL